secrets:
  - name: JBOSS_A_MQ_BROKER_PASSWORD
    value: amq
  - name: JBOSS_A_MQ_BROKER_USER
    value: amq
  - name: WALLET_MS_DB_PASSWORD
    value: welcome1
  - name: WALLET_MS_DB_USER
    value: postgres    