config_map:
  - name: JBOSS_A_MQ_BROKER_URL
    value: tcp://broker-amq-tcp.blockchain-demo-mq-green.svc:61616
  - name: WALLET_MS_JDBC_URL
    value: jdbc:postgresql://postgresql.blockchain-demo-database.svc:5432/blockchain-demo-prod-wallet-ms
  - name: JAEGER_SERVICE_NAME
    value: green-wallet-ms
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.blockchain-demo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.blockchain-demo-monitoring.svc      